language: python
python:
  - 2.7
  - 3.4
notifications:
  email:
    on_success: change
    on_failure: always
# whitelist
branches:
  only:
    - master
    - cython
sudo: false
addons:
  apt:
    packages:
    # GSL library
    - libgsl0-dev

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - conda update --yes openssl
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  #- sudo rm -rf /dev/shm
  #- sudo ln -s /run/shm /dev/shm
  # GSL library
  #- sudo apt-get install libgsl0ldbl libgsl0-dev
# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION cython numpy scipy matplotlib nose seaborn
  - pip install git+git://github.com/khrapovs/skewstudent
  - python setup.py build

# Run test
script:
  - python setup.py develop
  - nosetests

# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc
